<?php

use function Livewire\Volt\{title};

title('Bitwarden - Übersicht');

?>

<x-intranet-app-bitwarden::bitwarden-layout heading="Bitwarden App" subheading="Übersicht">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-bitwarden::bitwarden-layout>